/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Solar Impulse (https://sketchfab.com/solarimpulse)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/solar-impulse-flight-path-298e1ac1fdb048e892d036d588d4322c
title: Solar Impulse Flight Path
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function World(props) {
  const { nodes, materials } = useGLTF('/world.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={2.45} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/world.gltf')
